// See PRD section 27 (Roles and Permissions).

export enum Role {
  SUPER_ADMIN = "SUPER_ADMIN",
  BANK_ADMIN = "BANK_ADMIN",
  OPERATIONS = "OPERATIONS",
  COMPLIANCE_OFFICER = "COMPLIANCE_OFFICER",
  FINANCE_OFFICER = "FINANCE_OFFICER",
  CUSTOMER_SUPPORT = "CUSTOMER_SUPPORT",
  CUSTOMER = "CUSTOMER",
  API_CLIENT = "API_CLIENT",
  // Machine-only identity minted by one service to call another (e.g.
  // transfer-service posting to ledger-service mid-saga). Never issued to a
  // human via /v1/auth/login, and deliberately excluded from STAFF_ROLES.
  SERVICE = "SERVICE",
}

export enum Permission {
  TRANSFER_CREATE = "transfer:create",
  TRANSFER_APPROVE = "transfer:approve",
  TRANSFER_CANCEL = "transfer:cancel",
  ACCOUNT_CREATE = "account:create",
  ACCOUNT_FREEZE = "account:freeze",
  ACCOUNT_UNFREEZE = "account:unfreeze",
  ACCOUNT_CLOSE = "account:close",
  ACCOUNT_ACTIVATE = "account:activate",
  ACCOUNT_READ = "account:read",
  CUSTOMER_READ = "customer:read",
  CUSTOMER_UPDATE = "customer:update",
  KYC_SUBMIT = "kyc:submit",
  KYC_READ = "kyc:read",
  KYC_DECIDE = "kyc:decide",
  TRANSACTION_READ = "transaction:read",
  TRANSACTION_REVERSE = "transaction:reverse",
  LEDGER_POST = "ledger:post",
  LEDGER_TRANSFER = "ledger:transfer",
  FRAUD_READ = "fraud:read",
  NOTIFICATION_READ = "notification:read",
  PAYMENT_CREATE = "payment:create",
  PAYMENT_READ = "payment:read",
  CARD_ISSUE = "card:issue",
  CARD_READ = "card:read",
  CARD_BLOCK = "card:block",
  REPORTING_READ = "reporting:read",
  // Cross-tenant platform administration — listing tenants and the users
  // within them. Deliberately not granted to any role but SUPER_ADMIN.
  TENANT_READ = "tenant:read",
  // Creating tenant admins (staff accounts) for any tenant — a write action,
  // kept separate from TENANT_READ. Also SUPER_ADMIN-only.
  TENANT_MANAGE = "tenant:manage",
}

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [Role.SUPER_ADMIN]: Object.values(Permission),
  [Role.BANK_ADMIN]: [
    Permission.CUSTOMER_READ,
    Permission.CUSTOMER_UPDATE,
    Permission.ACCOUNT_READ,
    Permission.ACCOUNT_CREATE,
    Permission.ACCOUNT_FREEZE,
    Permission.ACCOUNT_UNFREEZE,
    Permission.ACCOUNT_CLOSE,
    Permission.ACCOUNT_ACTIVATE,
    Permission.KYC_READ,
    Permission.KYC_DECIDE,
    Permission.TRANSACTION_READ,
    Permission.LEDGER_POST,
    Permission.FRAUD_READ,
    Permission.NOTIFICATION_READ,
    Permission.PAYMENT_READ,
    Permission.CARD_READ,
    Permission.CARD_BLOCK,
    Permission.REPORTING_READ,
  ],
  [Role.OPERATIONS]: [
    Permission.CUSTOMER_READ,
    Permission.CUSTOMER_UPDATE,
    Permission.ACCOUNT_READ,
    Permission.ACCOUNT_CREATE,
    Permission.ACCOUNT_ACTIVATE,
    Permission.ACCOUNT_FREEZE,
    Permission.ACCOUNT_UNFREEZE,
    Permission.KYC_SUBMIT,
    Permission.TRANSACTION_READ,
    Permission.TRANSFER_CANCEL,
    Permission.FRAUD_READ,
    Permission.NOTIFICATION_READ,
    Permission.PAYMENT_READ,
    Permission.CARD_READ,
    Permission.CARD_BLOCK,
    Permission.REPORTING_READ,
  ],
  [Role.COMPLIANCE_OFFICER]: [
    Permission.CUSTOMER_READ,
    Permission.KYC_READ,
    Permission.KYC_DECIDE,
    Permission.TRANSACTION_READ,
    Permission.TRANSACTION_REVERSE,
    Permission.FRAUD_READ,
    Permission.NOTIFICATION_READ,
    Permission.REPORTING_READ,
  ],
  [Role.FINANCE_OFFICER]: [
    Permission.TRANSACTION_READ,
    Permission.TRANSACTION_REVERSE,
    Permission.LEDGER_POST,
    Permission.NOTIFICATION_READ,
    Permission.PAYMENT_READ,
    Permission.REPORTING_READ,
  ],
  [Role.CUSTOMER_SUPPORT]: [
    Permission.CUSTOMER_READ,
    Permission.ACCOUNT_READ,
    Permission.KYC_READ,
    Permission.TRANSACTION_READ,
    Permission.NOTIFICATION_READ,
    Permission.PAYMENT_READ,
    Permission.CARD_READ,
  ],
  [Role.CUSTOMER]: [
    Permission.CUSTOMER_READ,
    Permission.CUSTOMER_UPDATE,
    Permission.ACCOUNT_READ,
    Permission.ACCOUNT_CREATE,
    Permission.KYC_SUBMIT,
    Permission.KYC_READ,
    Permission.TRANSACTION_READ,
    Permission.TRANSFER_CREATE,
    Permission.TRANSFER_CANCEL,
    Permission.NOTIFICATION_READ,
    Permission.PAYMENT_CREATE,
    Permission.PAYMENT_READ,
    Permission.CARD_ISSUE,
    Permission.CARD_READ,
    Permission.CARD_BLOCK,
    Permission.REPORTING_READ,
  ],
  [Role.API_CLIENT]: [Permission.TRANSFER_CREATE, Permission.TRANSACTION_READ],
  [Role.SERVICE]: [Permission.LEDGER_TRANSFER],
};

// Roles that act on behalf of the bank rather than as an individual
// customer — used to gate "any record in my tenant" access vs. "only my
// own record" access on customer-facing resources.
export const STAFF_ROLES: Role[] = [
  Role.SUPER_ADMIN,
  Role.BANK_ADMIN,
  Role.OPERATIONS,
  Role.COMPLIANCE_OFFICER,
  Role.FINANCE_OFFICER,
  Role.CUSTOMER_SUPPORT,
];
